### ISSUE TITLE
AppInfo Bean Registration Error

### ISSUE THREAD

**Issue by ctoestreich** [micronaut-projects/micronaut-kafka#126]
Seeing the following error when we are running micronaut kafka apps.  Some info sanitized.

```
2020-05-05 11:33:34.826 CDT  WARN   - [pool-6-thread-2] Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.producer:type=app-info,id=xxxxxxxxx-event-transformer-service
	at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:423)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:297)
	at io.micronaut.configuration.kafka.KafkaProducerFactory.createProducer(KafkaProducerFactory.java:67)
	at io.micronaut.configuration.kafka.$KafkaProducerFactory$CreateProducer0Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1680)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:787)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:719)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:130)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.lambda$getProducer$15(KafkaClientIntroductionAdvice.java:620)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.getProducer(KafkaClientIntroductionAdvice.java:542)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.intercept(KafkaClientIntroductionAdvice.java:132)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:73)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:69)
	at xxxxxxxxx.xxxxxxxxx.event.client.XxxxxxxxxEventKafkaClient$Intercepted.publishEvent(Unknown Source)
	at xxxxxxxxx.xxxxxxxxx.event.processor.XxxxxxxxxEventRawProcessor.lambda$receive$0(XxxxxxxxxEventRawProcessor.java:40)
	at java.util.Optional.ifPresent(Optional.java:159)
	at xxxxxxxxx.xxxxxxxxx.event.processor.XxxxxxxxxEventRawProcessor.receive(XxxxxxxxxEventRawProcessor.java:40)
	at xxxxxxxxx.xxxxxxxxx.event.processor.$XxxxxxxxxEventRawProcessorDefinition$$exec1.invokeInternal(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethod.invoke(AbstractExecutableMethod.java:146)
	at io.micronaut.core.bind.DefaultExecutableBinder$1.invoke(DefaultExecutableBinder.java:109)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:496)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:143)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by graemerocher** [comment]
This happens if you use the same id for 2 different producers

**Comment by ctoestreich** [comment]
Yes but that is the default behavior. The only work around us using two different names configuration that both specify a unique client.id. Just having named confirms doesn’t solve it alone.

**Comment by ctoestreich** [comment]
Can keep not a big but I think I will post some info in docs about this. Unfortunately the work magic work around via framework would require injecting app name plus random hash As ‘client.id’ if not provided in app config.
