### ISSUE TITLE
kafka-streams application throws UnsatisfiedLinkError with openjdk:14-alpine in docker

### ISSUE THREAD

**Issue by ilkin** [micronaut-projects/micronaut-kafka#162]
kafka-streams application throws below error with openjdk:14-alpine in docker. openjdk:14-slim or openjdk:8-slim solved my problem and found some answers:

- [unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li](https://stackoverflow.com/questions/50288034/unsatisfiedlinkerror-tmp-snappy-1-1-4-libsnappyjava-so-error-loading-shared-li/51655643)
- [alternative-to-openjdk8-alpine-for-kafka-streams](https://stackoverflow.com/questions/54984418/alternative-to-openjdk8-alpine-for-kafka-streams)

`17:26:58.863 [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] DEBUG org.apache.kafka.clients.consumer.KafkaConsumer - [Consumer clientId=my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1-restore-consumer, groupId=null] Kafka consumer has been closed
17:26:58.863 [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] INFO org.apache.kafka.streams.processor.internals.StreamThread - stream-thread [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] State transition from PENDING_SHUTDOWN to DEAD
17:26:58.863 [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] INFO org.apache.kafka.streams.KafkaStreams - stream-client [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e] State transition from REBALANCING to ERROR
17:26:58.863 [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] ERROR org.apache.kafka.streams.KafkaStreams - stream-client [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e] All stream threads have died. The instance will be in error state and should be closed.
17:26:58.863 [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] INFO org.apache.kafka.streams.processor.internals.StreamThread - stream-thread [my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1] Shutdown complete
Exception in thread "my-app-5d83364e-6bd1-4533-a3d7-69ca341ba95e-StreamThread-1" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6692981191526015936.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/librocksdbjni6692981191526015936.so)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2452)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2508)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2704)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2637)
	at java.base/java.lang.Runtime.load0(Runtime.java:745)
	at java.base/java.lang.System.load(System.java:1871)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at org.rocksdb.DBOptions.<clinit>(DBOptions.java:21)
	at org.apache.kafka.streams.state.internals.RocksDBStore.openDB(RocksDBStore.java:133)
	at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:229)
	at org.apache.kafka.streams.state.internals.WrappedStateStore.init(WrappedStateStore.java:48)
	at org.apache.kafka.streams.state.internals.ChangeLoggingKeyValueBytesStore.init(ChangeLoggingKeyValueBytesStore.java:44)
	at org.apache.kafka.streams.state.internals.WrappedStateStore.init(WrappedStateStore.java:48)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:58)
	at org.apache.kafka.streams.state.internals.WrappedStateStore.init(WrappedStateStore.java:48)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.lambda$init$0(MeteredKeyValueStore.java:101)
	at org.apache.kafka.streams.processor.internals.metrics.StreamsMetricsImpl.maybeMeasureLatency(StreamsMetricsImpl.java:806)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.init(MeteredKeyValueStore.java:101)
	at org.apache.kafka.streams.processor.internals.AbstractTask.registerStateStores(AbstractTask.java:210)
	at org.apache.kafka.streams.processor.internals.StreamTask.initializeStateStores(StreamTask.java:275)
	at org.apache.kafka.streams.processor.internals.AssignedTasks.initializeNewTasks(AssignedTasks.java:76)
	at org.apache.kafka.streams.processor.internals.TaskManager.updateNewAndRestoringTasks(TaskManager.java:397)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:779)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)`

**Comment by graemerocher** [comment]
I doubt this has anything to do with Micronaut Kafka.. have you reported the issue to the Kafka issue tracker?

**Comment by ilkin** [comment]
Unfortunately no. I also doubt, but this case can note in Micronaut Kafka documentation.

**Comment by guillermocalvo** [comment]
It's been 1+ year since Docker Hub officially deprecated OpenJDK images, so I think it's safe to close this issue now.

A list of suitable replacements can be found in the [deprecation notice](https://hub.docker.com/_/openjdk).
