### ISSUE TITLE
With multiple receivers in Kafka Listener causes javax.management.InstanceAlreadyExistsException

### ISSUE THREAD

**Issue by RaviH** [micronaut-projects/micronaut-kafka#2]
Similar to / same as: https://github.com/micronaut-projects/micronaut-core/issues/446

Same exception, except I am using micronaut `1.0.4`

Project is attached: [kafka-sample.zip](https://github.com/micronaut-projects/micronaut-core/files/2826258/kafka-sample.zip)

Expects Kafka to be running at **localhost:9092** : `docker run -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=127.0.0.1 --env ADVERTISED_PORT=9092 spotify/kafka`

```
@KafkaListener(offsetReset = OffsetReset.EARLIEST)
public class ProductListener {

    private static final Logger logger = LoggerFactory.getLogger(ProductListener.class);

    @Topic("my-products")
    public void receive(@KafkaKey String brand, String name) {
        logger.info("Got Product - {} by {}", brand, name);
    }

    @Topic("my-products-2")
    public void receive2(@KafkaKey String key, LineupInfo lineupInfo) {
        logger.info("Got Lineup info - {} by {}", key, lineupInfo);
    }
}
```
Stack trace:
```
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=lineupcacheservice-product-listener
    at com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:437) ~[na:1.8.0_162]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1898) ~[na:1.8.0_162]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:966) ~[na:1.8.0_162]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:900) ~[na:1.8.0_162]
    at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:324) ~[na:1.8.0_162]
    at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522) ~[na:1.8.0_162]
    at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:62) ~[kafka-clients-2.0.0.jar:na]
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:791) [kafka-clients-2.0.0.jar:na]
    at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650) [kafka-clients-2.0.0.jar:na]
    at io.micronaut.configuration.kafka.KafkaConsumerFactory.createConsumer(KafkaConsumerFactory.java:59) [micronaut-kafka-1.0.0.jar:1.0.0]
    at io.micronaut.configuration.kafka.$KafkaConsumerFactory$CreateConsumerDefinition.doBuild(Unknown Source) [micronaut-kafka-1.0.0.jar:1.0.0]
    at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:113) [micronaut-inject-1.0.0.jar:1.0.0]
    at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1303) [micronaut-inject-1.0.0.jar:1.0.0]
    at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:660) [micronaut-inject-1.0.0.jar:1.0.0]
    at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:598) [micronaut-inject-1.0.0.jar:1.0.0]
    at io.micronaut.context.BeanContext.createBean(BeanContext.java:126) [micronaut-inject-1.0.0.jar:1.0.0]
    at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.process(KafkaConsumerProcessor.java:262) [micronaut-kafka-1.0.0.jar:1.0.0]
```

**Comment by eriknyk** [comment]
Still happening on 2.0.0, event If I set the 

```
@KafkaListener(clientId="any-non-existent-other", ...
```

Output (only on bootstrap):
```
11:02:14.850 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version: 2.4.0
11:02:14.851 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId: 77a89fcf8d7fa018
11:02:14.851 [main] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1587830534850
11:03:18.423 [main] WARN  o.a.kafka.common.utils.AppInfoParser - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=ssss
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(DefaultMBeanServerInterceptor.java:1855)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(DefaultMBeanServerInterceptor.java:955)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:890)
	at java.management/com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at java.management/com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
	at org.apache.kafka.common.utils.AppInfoParser.registerAppInfo(AppInfoParser.java:64)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:814)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
	at io.micronaut.configuration.kafka.KafkaConsumerFactory.createConsumer(KafkaConsumerFactory.java:95)
	at io.micronaut.configuration.kafka.$KafkaConsumerFactory$CreateConsumer0Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractParametrizedBeanDefinition.build(AbstractParametrizedBeanDefinition.java:117)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1694)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:796)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:723)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:130)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.process(KafkaConsumerProcessor.java:315)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.process(KafkaConsumerProcessor.java:87)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:89)
	at io.micronaut.context.AnnotationProcessorListener.onCreated(AnnotationProcessorListener.java:45)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1763)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2761)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2650)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:660)
	at io.micronaut.context.DefaultBeanContext.streamOfType(DefaultBeanContext.java:647)
	at io.micronaut.context.DefaultBeanContext.lambda$initializeContext$29(DefaultBeanContext.java:1420)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1419)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2575)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:211)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at com.tiercollect.services.kiphu.Application.main(Application.java:7)
```

Best Regards
