### ISSUE TITLE
Exception when enabling Prometheus and Kafka

### ISSUE THREAD

**Issue by goeh** [micronaut-projects/micronaut-kafka#37]
When enabling Prometheus in a Micronaut application that includes Kafka consumers, multiple exception messages are written to the log.

**Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'kafka_producer_request_latency_max' containing tag keys [client_id]. The meter you are attempting to register has keys [client_id, node_id].**

The meter name varies.

Another developer with same issue: https://stackoverflow.com/questions/53829941/prometheus-metrics-of-kafka-consumer-with-micronaut-throws-illegalargumentexcept

I will try to create a sample application in a few days.

### Steps to Reproduce

1. Add compile dependency "io.micronaut.configuration:micronaut-kafka"
2. Add compile dependency "io.micronaut.configuration:micronaut-micrometer-registry-prometheus"
3. Configure Prometheus

```
micronaut:
    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
```

### Expected Behaviour

No exception messages.

### Actual Behaviour

Application starts ok but an exception is thrown multiple times. Makes it harder to search logs for other issues because this exception takes up lot of log space.

```
Error when registering metric on io.micronaut.configuration.kafka.metrics.ProducerKafkaMetricsReporter","logger_name":"org.apache.kafka.common.metrics.Metrics","thread_name":"kafka-producer-network-thread | producer-1","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter named 'kafka_producer_request_latency_max' containing tag keys [client_id]. The meter you are attempting to register has keys [client_id, node_id].
    at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$collectorByName$9(PrometheusMeterRegistry.java:372)
    at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
    at io.micrometer.prometheus.PrometheusMeterRegistry.collectorByName(PrometheusMeterRegistry.java:359)
    at io.micrometer.prometheus.PrometheusMeterRegistry.newGauge(PrometheusMeterRegistry.java:230)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:257)
    at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:521)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:575)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:528)
    at io.micrometer.core.instrument.MeterRegistry.registerMeterIfNecessary(MeterRegistry.java:521)
    at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:257)
    at io.micrometer.core.instrument.Gauge$Builder.register(Gauge.java:190)
    at io.micrometer.core.instrument.MeterRegistry.gauge(MeterRegistry.java:433)
    at io.micronaut.configuration.kafka.metrics.AbstractKafkaMetricsReporter.registerMetric(AbstractKafkaMetricsReporter.java:100)
    at io.micronaut.configuration.kafka.metrics.AbstractKafkaMetricsReporter.metricChange(AbstractKafkaMetricsReporter.java:65)
    at io.micronaut.configuration.kafka.metrics.ProducerKafkaMetricsReporter.metricChange(ProducerKafkaMetricsReporter.java:26)
    at org.apache.kafka.common.metrics.Metrics.registerMetric(Metrics.java:568)
    at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:284)
    at org.apache.kafka.common.metrics.Sensor.add(Sensor.java:260)
    at org.apache.kafka.common.network.Selector$SelectorMetrics.maybeRegisterConnectionMetrics(Selector.java:1113)
    at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:508)
    at org.apache.kafka.common.network.Selector.poll(Selector.java:467)
    at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:535)
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:311)
    at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:235)
    at java.lang.Thread.run(Thread.java:748)
```

### Environment Information

- **Operating System**: MacOS 10.14.5
- **Micronaut Version:** 1.1.2
- **JDK Version:** 1.8.0_202

### Example Application

- https://github.com/goeh/issue-kafka-37

**Comment by rabend** [comment]
I have the same problem. The [documentation](https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaMetrics) says to disable kafka metrics by setting `micronaut.metrics.kafka.enabled=false`, but this does not solve the issue for me. Plus, this would mean that my application would not produce _any_ kafka metrics, which I also don't want.
Could you try setting the property anyway and see if it does something for you?

**Comment by graemerocher** [comment]
I think this is probably because both the consumer and the producer are using the same metric names? @ctoestreich is this the case?

**Comment by ctoestreich** [comment]
I will look at it tomorrow.

**Comment by goeh** [comment]
The difference seems to be Micrometer **tags**. The existing meter have the following name and tags:
```
MeterId{name='kafka.consumer.outgoing-byte-total', tags=[tag(client-id=kafka37-test-listener)]}
```
While the new meter has an extra tag:
```
MeterId{name='kafka.consumer.outgoing-byte-total', tags=[tag(client-id=kafka37-test-listener),tag(node-id=node--1)]}
```
This situation causes an exception here https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L379

I don't know why and where it could be fixed.

**Comment by goeh** [comment]
Sample application here: https://github.com/goeh/issue-kafka-37

**Comment by graemerocher** [comment]
I pushed a fix that limits the tags used to register to only the client-id otherwise the tags seem to change per consumer. Users can still customize this behaviour by overriding the `ConsumerKafkaMetricsReporter` bean

**Comment by webkitez** [comment]
@goeh is this issue resolved.. what did u do ?

**Comment by goeh** [comment]
The fix seems to have solved the exception. As far as I can remember, I've not seen the exception in dev/staging since last summer. Disclaimer: We have not enabled prometheus in production yet.

**Comment by webkitez** [comment]
what version are you using if u can tell me that? @goeh

**Comment by goeh** [comment]
@webkitez Micronaut 1.2.10
