### ISSUE TITLE
Problem with using Kafka client on OCI streams

### ISSUE THREAD

**Issue by ie-senol** [micronaut-projects/micronaut-kafka#530]
### Expected Behavior

The same Kafka producer could send messages to OCI streams with an appropriate configuration.

### Actual Behaviour

```
15:52:41.753 [io-executor-thread-2] INFO  o.a.k.clients.producer.KafkaProducer - [Producer clientId=SCHEDULER-POLLER] Closing the Kafka producer with timeoutMillis = 0 ms.
15:52:41.753 [io-executor-thread-2] INFO  o.a.kafka.common.metrics.Metrics - Metrics scheduler closed
15:52:41.753 [io-executor-thread-2] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter io.micronaut.configuration.kafka.metrics.ProducerKafkaMetricsReporter
15:52:41.754 [io-executor-thread-2] INFO  o.a.kafka.common.metrics.Metrics - Closing reporter org.apache.kafka.common.metrics.JmxReporter
15:52:41.754 [io-executor-thread-2] INFO  o.a.kafka.common.metrics.Metrics - Metrics reporters closed
15:52:41.756 [io-executor-thread-2] INFO  o.a.kafka.common.utils.AppInfoParser - App info kafka.producer for SCHEDULER-POLLER unregistered
15:52:41.760 [io-executor-thread-2] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.oracle.gbu.gaes.schedulerpoller.kafka.StepInstanceProducer$Intercepted] executed with error: Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2365)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1128)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:1054)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:180)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.lambda$getProducer$35(KafkaClientIntroductionAdvice.java:702)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.getProducer(KafkaClientIntroductionAdvice.java:488)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.intercept(KafkaClientIntroductionAdvice.java:126)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.oracle.gbu.gaes.schedulerpoller.kafka.StepInstanceProducer$Intercepted.send(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.DemoController.sendEventToKafka(DemoController.java:55)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Intercepted.$$access$$sendEventToKafka(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Intercepted.sendEventToKafka(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
	at io.micronaut.configuration.kafka.KafkaProducerFactory.getProducer(KafkaProducerFactory.java:105)
	at io.micronaut.configuration.kafka.$KafkaProducerFactory$GetProducer0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:755)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2323)
	... 39 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429)
	... 46 common frames omitted
15:52:41.783 [io-executor-thread-1] ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2365)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1128)
	at io.micronaut.context.DefaultBeanContext.createBean(DefaultBeanContext.java:1054)
	at io.micronaut.context.BeanContext.createBean(BeanContext.java:180)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.lambda$getProducer$35(KafkaClientIntroductionAdvice.java:702)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.getProducer(KafkaClientIntroductionAdvice.java:488)
	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.intercept(KafkaClientIntroductionAdvice.java:126)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:92)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.oracle.gbu.gaes.schedulerpoller.kafka.StepInstanceProducer$Intercepted.send(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.DemoController.sendEventToKafka(DemoController.java:55)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Intercepted.$$access$$sendEventToKafka(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:128)
	at io.micronaut.validation.ValidatingInterceptor.intercept(ValidatingInterceptor.java:138)
	at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Intercepted.sendEventToKafka(Unknown Source)
	at com.oracle.gbu.gaes.schedulerpoller.controller.$DemoController$Definition$Exec.dispatch(Unknown Source)
	at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378)
	at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:583)
	at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)
	at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)
	at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)
	at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)
	at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)
	at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
	at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$null$0(ReactorInstrumentation.java:62)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)
	at io.micrometer.core.instrument.composite.CompositeTimer.recordCallable(CompositeTimer.java:68)
	at io.micrometer.core.instrument.Timer.lambda$wrap$1(Timer.java:171)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:440)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:291)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:318)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:303)
	at io.micronaut.configuration.kafka.KafkaProducerFactory.getProducer(KafkaProducerFactory.java:105)
	at io.micronaut.configuration.kafka.$KafkaProducerFactory$GetProducer0$Definition.doBuild(Unknown Source)
	at io.micronaut.context.AbstractInitializableBeanDefinition.build(AbstractInitializableBeanDefinition.java:755)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2323)
	... 39 common frames omitted
Caused by: java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
	at org.apache.kafka.common.security.JaasContext.defaultContext(JaasContext.java:131)
	at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:96)
	at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:448)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:429)
	... 46 common frames omitted
```

### Steps To Reproduce

- graalvm-ee-java11-21.3.0
- micronaut 3.4.1
```xml
<parent>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-bom</artifactId>
    <version>3.4.1</version>
 </parent>
```
which uses **micronaut-kafka** 4.2.0
```xml
  <modelVersion>4.0.0</modelVersion>
  <groupId>io.micronaut</groupId>
  <artifactId>micronaut-bom</artifactId>
  <version>3.4.1</version>

 <micronaut.kafka.version>4.2.0</micronaut.kafka.version>
```
- I set the following environment variables in my run/debug configuration variables in IntelliJ IDEA (masked some of the actual ones for privacy):
```properties
KAFKA_HOST=localhost;
KAFKA_PORT=9092;

OCI_STREAMS_BOOTSTRAP_SERVER=cell-1.streaming.us-ashburn-1.oci.oraclecloud.com;
OCI_STREAMS_BOOTSTRAP_SERVER_PORT=9092;
OCI_STREAMS_TENANCY_NAME=GBUCDSINT;
OCI_STREAMS_USER_NAME=oracle\/IBRAHIM.SENOL@ORACLE.COM;
OCI_STREAMS_STREAM_POOL_OCID=ocid1.streampool.oc1.iad.<<deleted>>;
OCI_STREAMS_AUTH_TOKEN=<<deleted>>;

micronaut.env.deduction=false;
micronaut.environments=dev;
MICRONAUT_ENVIRONMENTS=dev; 
```
- I use the environment variables above to set the Kafka & OCI configuration in my **application.yml** file:

```yaml
# Option-1: Using Apache Kafka
#kafka:
#  bootstrap:
#    servers: ${KAFKA_HOST}:${KAFKA_PORT}
#  producers:
#    SCHEDULER-POLLER:
#      acks: all
#      retries: 5

# Option-2: Using the OCI Streams via Kafka
kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${OCI_STREAMS_BOOTSTRAP_SERVER}:${OCI_STREAMS_BOOTSTRAP_SERVER_PORT}
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jass:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${OCI_STREAMS_TENANCY_NAME}/${OCI_STREAMS_USER_NAME}/${OCI_STREAMS_STREAM_POOL_OCID}" password="${OCI_STREAMS_AUTH_TOKEN}";
  key:
    serializer: org.apache.kafka.common.serialization.StringSerializer
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value:
    serializer: org.apache.kafka.common.serialization.StringSerializer
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producers:
    SCHEDULER-POLLER:
      acks: all
      retries: 5
```
- Here is my Kafka producer:

```java
import java.util.List;

import com.oracle.gbu.gaes.schedulerpoller.domain.StepInstance;
import io.micronaut.configuration.kafka.annotation.KafkaClient;
import io.micronaut.configuration.kafka.annotation.Topic;

@KafkaClient ( id = "SCHEDULER-POLLER" )
public interface StepInstanceProducer
{
  @Topic ( "${scheduler.event-topic:SCHEDULER-EVENTS}" )
  void send( StepInstance event );

  @Topic ( "${scheduler.event-topic:SCHEDULER-EVENTS}" )
  void send( List<StepInstance> events );
}
```
- And, these are the error messages from the exception I get when I tried to send a message to OCI stream:

```error
Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
...
Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is not set
...
ERROR i.m.http.server.RouteExecutor - Unexpected error occurred: Error instantiating bean of type [org.apache.kafka.clients.producer.Producer]: Failed to construct kafka producer
...
```

![image](https://user-images.githubusercontent.com/97619368/164785837-5c98eedb-dea2-447c-ae62-6c51ad62b53f.png)

### Environment Information

- graalvm-ee-java11-21.3.0
- macOS Monterey version 12.2.1

### Version

3.4.1

**Comment by ersinoracle** [comment]
When the same Kafka producer client ran on the Apache Kafka configuration instead, it gives sends the message and gives the following output:

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/97619368/164790678-6956cd6a-1d3e-49b6-a001-0943318c0907.png">

I also can consume the message on Apache Kafka:

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/97619368/164790875-0d1e6630-4da2-4b6d-bd93-b64ad7b87058.png">
<img width="2798" alt="image" src="https://user-images.githubusercontent.com/97619368/164790957-9705df28-b777-439f-8884-b9c4c7b2eb62.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/97619368/164791008-53720c05-5563-4f28-a78d-e6a9732aa481.png">

**Comment by ersinoracle** [comment]
I resolved the issue: the keyword `jaas` was written as `jass`. Fixing it has fixed the connection to OCI streams via `micronaut-kafka` problem.

```yaml
kafka:
  health:
    enabled: false
  bootstrap:
    servers: ${OCI_STREAMS_BOOTSTRAP_SERVER}:${OCI_STREAMS_BOOTSTRAP_SERVER_PORT}
  security:
    protocol: SASL_SSL
  sasl:
    mechanism: PLAIN
    jaas:
      config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${OCI_STREAMS_TENANCY_NAME}/${OCI_STREAMS_USER_NAME}/${OCI_STREAMS_STREAM_POOL_OCID}" password="${OCI_STREAMS_AUTH_TOKEN}";
  key:
    serializer: org.apache.kafka.common.serialization.StringSerializer
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value:
    serializer: org.apache.kafka.common.serialization.StringSerializer
    deserializer: org.apache.kafka.common.serialization.StringDeserializer
  retries: 5
  max:
    request:
      size: 1048576
    partition:
      fetch:
        bytes: 1048576
  group:
    id: XGBU-GTS
  producers:
    SCHEDULER-POLLER:
      acks: all
      retries: 5
```
```log
11:51:00.475 [io-executor-thread-2] INFO  o.a.k.c.s.a.AbstractLogin - Successfully logged in.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'key.deserializer' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'value.deserializer' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'group.id' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'max.partition.fetch.bytes' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'port' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'host' was supplied but isn't a known config.
11:51:00.608 [io-executor-thread-2] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'health.enabled' was supplied but isn't a known config.
11:51:00.611 [io-executor-thread-2] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version: 2.8.0
11:51:00.612 [io-executor-thread-2] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId: ebb1d6e21cc92130
11:51:00.612 [io-executor-thread-2] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka startTimeMs: 1650901860608
```

However, now I cannot send any message to a topic that already exists in OCI streams. 

I receive an error message telling `Topic not present in metadata'.

```log
11:51:08.827 [kafka-producer-network-thread | SCHEDULER-POLLER] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=SCHEDULER-POLLER] Bootstrap broker cell-1.streaming.us-ashburn-1.oci.oraclecloud.com:9092 (id: -1 rack: null) disconnected
11:51:27.417 [kafka-producer-network-thread | SCHEDULER-POLLER] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=SCHEDULER-POLLER] Bootstrap broker cell-1.streaming.us-ashburn-1.oci.oraclecloud.com:9092 (id: -1 rack: null) disconnected
11:51:54.812 [kafka-producer-network-thread | SCHEDULER-POLLER] WARN  o.apache.kafka.clients.NetworkClient - [Producer clientId=SCHEDULER-POLLER] Bootstrap broker cell-1.streaming.us-ashburn-1.oci.oraclecloud.com:9092 (id: -1 rack: null) disconnected
11:52:00.627 [io-executor-thread-2] ERROR i.m.r.intercept.RecoveryInterceptor - Type [com.oracle.gbu.gaes.schedulerpoller.kafka.StepInstanceProducer$Intercepted] executed with error: Exception sending producer record for method [void send(StepInstance event)]: org.apache.kafka.common.errors.TimeoutException: Topic SCHEDULER-EVENTS not present in metadata after 60000 ms.

Caused by: org.apache.kafka.common.errors.TimeoutException: Topic SCHEDULER-EVENTS not present in metadata after 60000 ms.
```
However the topic exists:

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/97619368/165131243-a86b0b13-75ce-4522-9238-5d7ec3f260d4.png">

Could you please help?

**Comment by ie-senol** [comment]
Any updates?

**Comment by graemerocher** [comment]
Tracked by an internal ticket

**Comment by ie-senol** [comment]
@burtbeckwith had provided a sample code which didn't work on my side. I'm getting the the same error message when I run his sample code:

`io.micronaut.messaging.exceptions.MessagingClientException: Exception sending producer record for method [void send(StepInstance event)]: org.apache.kafka.common.errors.TimeoutException: Topic SCHEDULER-EVENTS not present in metadata after 60000 ms.`

The stream exists and is active though.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/97619368/207381653-2ff75fa7-0f63-4d5b-b491-4dbf536496c6.png">


Could you please help?

**Comment by ie-senol** [comment]
After turning off the VPN, the sample application worked successfully. Thank you for the help.
