### ISSUE TITLE
Batch and Acknowledgement are mutually exclusive

### ISSUE THREAD

**Issue by paulolieuthier** [micronaut-projects/micronaut-kafka#54]
Can't get batch and receive Acknowledgement at the same time.

Code sample:
```
@KafkaListener(groupId = "group-name", batch = true)
public class MessageKafkaConsumer {
    @Topic("topic-name")
    public void call(List<Message> message, Acknowledgement acknowledgement) {
        // ...
        acknowledgement.ack();
    }
}
```

Error message:
```
10:52:15.739 [pool-2-thread-1] ERROR i.m.c.k.e.KafkaListenerExceptionHandler - Kafka consumer [MessageKafkaConsumer@4e00663b] produced error: Required argument [Acknowledgement acknowledgement] not specified
io.micronaut.core.bind.exceptions.UnsatisfiedArgumentException: Required argument [Acknowledgement acknowledgement] not specified
	at io.micronaut.core.bind.DefaultExecutableBinder.bind(DefaultExecutableBinder.java:96)
	at io.micronaut.configuration.kafka.processor.KafkaConsumerProcessor.lambda$process$7(KafkaConsumerProcessor.java:421)
	at io.micrometer.core.instrument.composite.CompositeTimer.record(CompositeTimer.java:79)
	at io.micrometer.core.instrument.Timer.lambda$wrap$0(Timer.java:143)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

If I remove `batch = true` it works.

**Comment by paulolieuthier** [comment]
Will be using `org.apache.kafka.clients.consumer.Consumer` and `Consumer::commitSync()` for now.

**Comment by hmatt1** [comment]
`Acknowledgement` isn't supported for Kafka, even without the `batch`: 

https://github.com/micronaut-projects/micronaut-kafka/blob/0c6435e7ce1c8815e7c9c35b4f1c55d07d300c7a/kafka/src/main/java/io/micronaut/configuration/kafka/KafkaAcknowledgement.java

**Comment by paulolieuthier** [comment]
From the link:

> Kafka does not support rejection of messages explicitly.

OK, but it supports manual committing. `Acknowledgment` works for that. Just not if consuming in batches.
