### ISSUE TITLE
Micronaut Kafka GraalVM test app fails for 22.2.0

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-kafka#574]
https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2775259511

see: https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.jcp.xml.dsig.internal.dom.ApacheCanonicalizer.<clinit>() 
[93](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L93)Parsing context: <no parsing context available> 
[94](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L94)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:152)
[95](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L95)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
[96](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L96)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
[97](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L97)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
[98](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L98)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultAnalysisPolicy.staticRootMethodGraph(DefaultAnalysisPolicy.java:182)
[99](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L99)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis.lambda$addRootMethod$0(PointsToAnalysis.java:458)
[100](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L100)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$2.run(PointsToAnalysis.java:658)
[101](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L101)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
[102](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L102)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
[103](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L103)	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[104](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L104)	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[105](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L105)	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[106](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L106)	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[107](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L107)	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[108](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L108)	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[109](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L109)Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of com.sun.org.slf4j.internal.Logger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=com.sun.org.slf4j.internal.Logger.
[110](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L110)	at parsing com.sun.org.apache.xml.internal.security.Init.init(Init.java:106)
[111](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L111)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2506)
[112](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L112)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:105)
[113](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L113)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3367)
[114](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L114)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3319)
[115](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L115)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3164)
[116](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L116)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
[117](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L117)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
[118](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L118)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
[119](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L119)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:79)
[120](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L120)	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
[121](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L121)	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:261)
[122](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L122)	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
[123](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L123)	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
[124](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L124)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
[125](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L125)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
[126](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L126)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.lookupEncodedGraph(InlineBeforeAnalysis.java:180)
[127](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L127)	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.doInline(PEGraphDecoder.java:1162)
[128](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L128)	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.tryInline(PEGraphDecoder.java:1145)
[129](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L129)	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.trySimplifyInvoke(PEGraphDecoder.java:1003)
[130](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L130)	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.handleInvoke(PEGraphDecoder.java:957)
[131](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L131)	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.processNextNode(GraphDecoder.java:817)
[132](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L132)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysisGraphDecoder.processNextNode(InlineBeforeAnalysis.java:240)
[133](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L133)	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.GraphDecoder.decode(GraphDecoder.java:548)
[134](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L134)	at jdk.internal.vm.compiler/org.graalvm.compiler.replacements.PEGraphDecoder.decode(PEGraphDecoder.java:833)
[135](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L135)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.phases.InlineBeforeAnalysis.decodeGraph(InlineBeforeAnalysis.java:98)
[136](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L136)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:176)
[137](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L137)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:343)
[138](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L138)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
[139](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L139)	... 13 more
[140](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L140)Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: No instances of com.sun.org.slf4j.internal.Logger are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=com.sun.org.slf4j.internal.Logger.
[141](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L141)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.checkImageHeapInstance(ClassInitializationFeature.java:140)
[142](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L142)	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.replaceObject(AnalysisUniverse.java:583)
[143](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L143)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.replaceObject(AnalysisConstantReflectionProvider.java:257)
[144](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L144)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.interceptValue(AnalysisConstantReflectionProvider.java:228)
[145](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L145)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readValue(AnalysisConstantReflectionProvider.java:105)
[146](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L146)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantReflectionProvider.readFieldValue(AnalysisConstantReflectionProvider.java:84)
[147](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L147)	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil$1.readValue(ConstantFoldUtil.java:55)
[148](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L148)	at jdk.internal.vm.compiler/org.graalvm.compiler.core.common.spi.JavaConstantFieldProvider.readConstantField(JavaConstantFieldProvider.java:78)
[149](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L149)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.ameta.AnalysisConstantFieldProvider.readConstantField(AnalysisConstantFieldProvider.java:72)
[150](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L150)	at jdk.internal.vm.compiler/org.graalvm.compiler.nodes.util.ConstantFoldUtil.tryConstantFold(ConstantFoldUtil.java:51)
[151](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L151)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.tryConstantFold(ConstantFoldLoadFieldPlugin.java:61)
[152](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L152)	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.ConstantFoldLoadFieldPlugin.handleLoadStaticField(ConstantFoldLoadFieldPlugin.java:57)
[153](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L153)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4753)
[154](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L154)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genGetStatic(BytecodeParser.java:4724)
[155](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L155)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5218)
[156](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L156)	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3359)
[157](https://gitlab.com/micronaut-projects/micronaut-graal-tests/-/jobs/2768790900#L157)	... 38 more
```

**Comment by timyates** [comment]
Weirdly, it works locally 😢 

We have two classpath errors here:

```
Warning: Could not resolve io.micronaut.configuration.kafka.metrics.ConsumerKafkaMetricsReporter for reflection configuration. Reason: java.lang.NoClassDefFoundError: io/micrometer/core/instrument/binder/MeterBinder.
Warning: Could not resolve io.micronaut.configuration.kafka.metrics.ProducerKafkaMetricsReporter for reflection configuration. Reason: java.lang.NoClassDefFoundError: io/micrometer/core/instrument/binder/MeterBinder.
```

As we do not export `MeterBinder` libraries from the kafka build

@sdelamo Should we add `@RequiresMetrics` to https://github.com/micronaut-projects/micronaut-kafka/blob/f809ff798b56e7264c4a5f1fc1395438fc53ec69/kafka/src/main/java/io/micronaut/configuration/kafka/metrics/package-info.java#L22

**Comment by timyates** [comment]
Ahhh, it only fails in 17 👍 working on it
