### ISSUE TITLE
Scraping kafka metrics logs errors

### ISSUE THREAD

**Issue by Cybermaxke** [micronaut-projects/micronaut-kafka#648]
### Expected Behavior

Scraping metrics shouldn't log an error.

### Steps To Reproduce

  1. Setup micronaut app with kafka and metrics using following versions
      - micronaut-kafka 4.5.0
      - micronaut-micrometer-registry-prometheus 4.7.0
      - kafka-clients 2.8.2
   2. Setup endpoint that scrapes metrics
   3. Scrape metrics from endpoint
```
2023-01-18T10:48:26.824+01:00 [default-nioEventLoopGroup-1-7] WARN  [internal.DefaultGauge] Failed to apply the value function for the gauge 'kafka.consumer.version'. Note that subsequent logs will be logged at debug level.
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Number (java.lang.String and java.lang.Number are in module java.base of loader 'bootstrap')
	at io.micronaut.configuration.kafka.metrics.builder.KafkaMetricMeterTypeBuilder.lambda$build$0(KafkaMetricMeterTypeBuilder.java:137) ~[micronaut-kafka-4.5.0.jar:4.5.0]
	at io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58) ~[micrometer-core-1.9.4.jar:1.9.4]
	at io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:48) ~[micrometer-core-1.9.4.jar:1.9.4]
	at io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:53) ~[micrometer-core-1.9.4.jar:1.9.4]
	at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newGauge$5(PrometheusMeterRegistry.java:335) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
	at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:75) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
	at io.prometheus.client.Collector.collect(Collector.java:46) ~[simpleclient-0.15.0.jar:?]
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:197) ~[simpleclient-0.15.0.jar:?]
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:212) ~[simpleclient-0.15.0.jar:?]
	at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:152) ~[simpleclient-0.15.0.jar:?]
	at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:71) ~[simpleclient_common-0.15.0.jar:?]
	at io.prometheus.client.exporter.common.TextFormat.writeFormat(TextFormat.java:53) ~[simpleclient_common-0.15.0.jar:?]
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:158) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:153) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:124) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
	at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:111) ~[micrometer-registry-prometheus-1.9.4.jar:1.9.4]
```

I already looked a bit where the issue is coming from:
1. Kafka registers the version metric here as a `String` https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/AppInfoParser.java#L93
2. Micronaut kafka tries to cast this `String` to `Number` here: https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka/src/main/java/io/micronaut/configuration/kafka/metrics/builder/KafkaMetricMeterTypeBuilder.java#L137

### Environment Information

Alpine + JDK 17 in K8s

### Version

4.5.0

**Comment by andrew-pedrosa-img** [comment]
I am also having this issue

**Comment by graemerocher** [comment]
Seems like you diagnosed the issue, would you like to send a PR?

**Comment by Cybermaxke** [comment]
What's the solution that we want for this issue? Do we actually need the version metric, or can we just ignore it? (retuning empty optional for `kafka.consumer.version`)

**Comment by guillermocalvo** [comment]
Closed by https://github.com/micronaut-projects/micronaut-kafka/pull/809
