### ISSUE TITLE
Kafka embedded and maps

### ISSUE THREAD

**Issue by Sabst** [micronaut-projects/micronaut-kafka#72]
The payload of some of my messages contain maps (initially Json).

All works well using a deployed Kafka Server but the associated tests using Kafka Embedded fail for some obscure reason.

A map like `[a: [b: 1]]` gets transformed into `[a:Map(b -> 1)]`.

Here is a sample test that shows the problem. Just add it next to KafkaListenerSpec in the annotation tests directory:

```
package io.micronaut.configuration.kafka.annotation

import groovy.transform.EqualsAndHashCode
import io.micronaut.configuration.kafka.config.AbstractKafkaConfiguration
import io.micronaut.context.ApplicationContext
import io.micronaut.core.util.CollectionUtils
import io.micronaut.messaging.MessageHeaders
import io.micronaut.runtime.server.EmbeddedServer
import io.reactivex.Single
import spock.lang.AutoCleanup
import spock.lang.Shared
import spock.lang.Specification
import spock.lang.Stepwise
import spock.util.concurrent.PollingConditions

@Stepwise
class KafkaMapListenerSpec extends Specification {

    @Shared
    @AutoCleanup
    EmbeddedServer embeddedServer = ApplicationContext.run(EmbeddedServer,
            CollectionUtils.mapOf(
                    "kafka.bootstrap.servers", 'localhost:${random.port}',
                    "micrometer.metrics.enabled", true,
                    'endpoints.metrics.sensitive', false,
                    AbstractKafkaConfiguration.EMBEDDED, true,
                    AbstractKafkaConfiguration.EMBEDDED_TOPICS, ["book-details"]
            )
    )

    @Shared
    @AutoCleanup
    ApplicationContext context = embeddedServer.applicationContext

    void "test POJO map consumer"() {
        when:
        MyClient myClient = context.getBean(MyClient)
        BookDetails book = myClient.sendReactive("Stephen King", new BookDetails(title: "The Stand", details: [characters: [redman: 'Stuart Redman']])).blockingGet()

        PollingConditions conditions = new PollingConditions(timeout: 30, delay: 1)

        PojoConsumer myConsumer = context.getBean(PojoConsumer)
        then:
        conditions.eventually {
            myConsumer.lastBook == book
            myConsumer.messageHeaders != null
        }
    }

    @KafkaClient
    static interface MyClient {
        @Topic("book-details")
        Single<BookDetails> sendReactive(@KafkaKey String key, BookDetails bookDetails)
    }

     @KafkaListener(offsetReset = OffsetReset.EARLIEST)
    static class PojoConsumer {
        BookDetails lastBook
        MessageHeaders messageHeaders

        @Topic("book-details")
        void receiveBook(BookDetails bookDetails, MessageHeaders messageHeaders) {
            lastBook = bookDetails
            this.messageHeaders = messageHeaders

        }
    }

    @EqualsAndHashCode
    static class BookDetails {
        String title
        Map details
    }

}
```

The current result using tag v1.2.0 is:

```
./gradlew kafka:test --tests io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec
(...)
io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec > test POJO map consumer FAILED
    Condition not satisfied after 30.00 seconds and 31 attempts
        at spock.util.concurrent.PollingConditions.within(PollingConditions.java:164)
        at spock.util.concurrent.PollingConditions.eventually(PollingConditions.java:134)
        at io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec.test POJO map consumer(KafkaMapListenerSpec.groovy:44)

        Caused by:
        Condition not satisfied:

        myConsumer.lastBook == book
        |          |        |  |
        |          |        |  <io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec$BookDetails@7b35d2dd title=The Stand details=[characters:[redman:Stuart Redman]]>
        |          |        false
        |          <io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec$BookDetails@7598e9e title=The Stand details=[characters:Map(redman -> Stuart Redman)]>
        <io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec$PojoConsumer@4e7aaa9c lastBook=io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec$BookDetails@7598e9e messageHeaders=io.micronaut.configuration.kafka.KafkaHeaders@7316557f>
            at io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec.test POJO map consumer_closure1(KafkaMapListenerSpec.groovy:45)
            at io.micronaut.configuration.kafka.annotation.KafkaMapListenerSpec.test POJO map consumer_closure1(KafkaMapListenerSpec.groovy)
            at groovy.lang.Closure.call(Closure.java:405)
            at spock.util.concurrent.PollingConditions.within(PollingConditions.java:158)

```

**Comment by graemerocher** [comment]
We are deprecating Kafka Embedded in favour of Test Containers in the next release so don't see us fixing this.

**Comment by Sabst** [comment]
>We are deprecating Kafka Embedded in favour of Test Containers in the next release so don't see us fixing this.
I still get an error using Micronaut Kafka 1.3.0. Is the support of Test Containers implemented in this version?
Can you share any information about this? I do not see anything in the documentation.

**Comment by Sabst** [comment]
Nevermind, I managed to have the tests working again using Test Containers.
That looks better than the old way (embedded mongo and kafka).
