### ISSUE TITLE
Allow null (log compaction tombstones) as a value for KafkaClient

### ISSUE THREAD

**Issue by jacqui932** [micronaut-projects/micronaut-kafka#8]
Kafka uses a message with a body of null as a tombstone when doing log compaction (see https://kafka.apache.org/documentation/#compaction).  At the moment, sending a null value results in an error:

io.micronaut.messaging.exceptions.MessagingClientException: Value cannot be null for method:

	at io.micronaut.configuration.kafka.intercept.KafkaClientIntroductionAdvice.intercept(KafkaClientIntroductionAdvice.java:194)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)
	at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:74)
	at io.micronaut.aop.MethodInterceptor.intercept(MethodInterceptor.java:41)
	at io.micronaut.aop.chain.InterceptorChain.proceed(InterceptorChain.java:147)

Kafka clients should be able to send null payloads to Kafka.

**Comment by dfeist** [comment]
Related issue subscribing to tombstone topic that may have tombstone messages #88

**Comment by dfeist** [comment]
While creating a test case to test fix deserialization for #88, I saw that JsonSerde is serializing null as a string "null" which I believe is incorrect.  So while this issue may be fixed for simple types, I'd consider it still open for POJO types serialized to JSON.
