### ISSUE TITLE
KafkaListener breaks on unauthorized topic

### ISSUE THREAD

**Issue by AjiTae** [micronaut-projects/micronaut-kafka#9]
`@KafkaListener` does not listen to all (or some - each run differs) `@Topic`'s , if at least one`@Topic` is not authorized by the broker.

Example kafka docker and service:
https://github.com/AjiTae/micronaut-unauthorized-listener-issue

**Comment by graemerocher** [comment]
In your example the listener fails with:

```
08:22:39.276 [pool-1-thread-4] ERROR i.m.c.k.e.KafkaListenerExceptionHandler - Kafka consumer [kafka.testing.service.kafka.KafkaTopicListener@adcfe50] produced error: No entry found for connection 0
java.lang.IllegalStateException: No entry found for connection 0
        at org.apache.kafka.clients.ClusterConnectionStates.nodeState(ClusterConnectionStates.java:330)
        at org.apache.kafka.clients.ClusterConnectionStates.disconnected(ClusterConnectionStates.java:134)
        at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:921)
        at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:287)
```

Is that the behaviour you are seeing too?

**Comment by ojebari-ma** [comment]
Can you please confirm if this is still an issue in the latest version of Micronaut?

**Comment by AjiTae** [comment]
> Can you please confirm if this is still an issue in the latest version of Micronaut?

Sorry, can't confirm or deny, I do frontend now. :)
