### ISSUE TITLE
Possibility to disable kafka-streams if no Stream is defined

### ISSUE THREAD

**Issue by fgrutsch** [micronaut-projects/micronaut-kafka#942]
### Issue description

Versions:
- micronaut: 3.10.0
- micronaut-kafka-streams: 4.5.4

I am currently running into the issue that as soon as I pull in the micronaut-kafka-streams dependency AND I don't define any Streams that the server doesn't start up. It fails with:

```
Message: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
Path Taken: KafkaStreams.kafkaStreams(String name,ConfiguredStreamBuilder builder,KafkaClientSupplier kafkaClientSupplier,KStream[] kStreams)
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [org.apache.kafka.streams.KafkaStreams] could not be loaded: Error instantiating bean of type  [org.apache.kafka.streams.KafkaStreams]

Message: Invalid topology: Topology has no stream threads and no global threads, must subscribe to at least one source topic or global table.
Path Taken: KafkaStreams.kafkaStreams(String name,ConfiguredStreamBuilder builder,KafkaClientSupplier kafkaClientSupplier,KStream[] kStreams)
        at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1921)
        at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:249)
        at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:3326)
        at io.micronaut.context.DefaultBeanContext.finalizeConfiguration(DefaultBeanContext.java:3684)
        at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:341)
        at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:194)
        at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
        at op.events.ApplicationKt.main(Application.kt:10)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [org.apache.kafka.streams.KafkaStreams]
```

I assume this comes from [here](https://github.com/micronaut-projects/micronaut-kafka/blob/master/kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java#L113C9-L113C21)  because `org.apache.kafka.streams.KafkaStreams` requires at least 1 Stream from my understanding.

I am aware of the `kafka.streams.default.start-kafka-streams` setting, however this only influences whether Kafka is started or not. With this configuration set to false, it is still required to have at list one Stream Bean defined.

Is this intended or is there a nice way to overcome this problem, right now we have something like this to avoid the startup problem:

```
@Factory
class MicronautKafkaStreamsDisabler {

    @Singleton
    @Requires(property = START_KAFKA_STREAMS_CONFIG, value = "false", defaultValue = "true")
    fun noOpStream(builder: ConfiguredStreamBuilder): KStream<String, ByteArray> =
        builder.stream("", Consumed.with(Serdes.String(), Serdes.ByteArray()))
}
```

By setting `kafka.streams.default.start-kafka-streams: false` this noOpStream Bean is created.

Use case: We have a project that has Kafka Consumers and Kafka Streams which are contained in a single docker image. On deployment, we want to run Consumers and Streams separately in different pods. So the pod that is running a consumer only will not have a Stream bean enabled.

**Comment by andycookiebit** [comment]
I have another use-case for this. I have a Kafka stream that when it starts, has a lot of messages to process. Great, but the app doesn't respond to HTTP requests which check if its healthy - which fail.

I'd like to be able to run the KafkaStreams explicitly when I'm ready (and inside another Thread!).

**Comment by byronwong-dev** [comment]
I think the implementation intention in this [#555](https://github.com/micronaut-projects/micronaut-kafka/pull/555) is that it wants to still load the stream in, but not starting it so that TopologyTestDriver can work with it

which is misleading on the configuration `start-kafka-streams` expectation, shouldn't we just have the stream not get loaded at all?

**Comment by byronwong-dev** [comment]
Think further on this, might be best to keep the ability to still load the stream but pause it, since it can be used for TopologyTestDriver, so it makes sense probably to introduce `enabled` property for each individual kafka streams for more control on if the streams should be initialized 

Added a PR that attempts to add in the ability to disable the kafka stream. #1128 

Hope the contributors can give some reviews & feedback

**Comment by scprek** [comment]
My use case is I have different micronaut environments. Some only want kafka for producers, but not streams. I therefore get this error in those environments that do not create a Kafka Stream. So instead of just disabling certain streams, it would be nice to have a catch all like kafka `micronaut.kafka.streams.enabled=false`.

So would that mean we need to disable ?
```java
@Factory
public class KafkaStreamsFactory implements Closeable {
```

**Comment by byronwong-dev** [comment]
@scprek in your case, you can control it via different application environment such as `application-streams.yml` which contains the kafka streams configuration? so that you run can you app with `micronaut.environments=streams` so that it loads only in environment that requires it

**Comment by scprek** [comment]
Yes I did that however I believe I hit an edge case where I needed Kafka but not Kafka streams in one micronaut environment. If you don't need any Kafka looks like it worked
