### ISSUE TITLE
native-image does not compile with JDK-11 (Works with JDK-8)

### ISSUE THREAD

**Issue by mhaddon** [micronaut-projects/micronaut-kafka#99]
If I package my project with JDK-11 (maven:3.6.3-jdk-11), then try to native-image compile the application with graalvm-ce:19.3.1 (oracle/graalvm-ce:19.3.1-java11).

You get errors similar to: 
```
Fatal error: org.graalvm.compiler.debug.GraalError: java.lang.NullPointerException
        at method: Checksum org.apache.kafka.common.utils.Crc32C$Java9ChecksumFactory.create()  [Direct call from long Crc32C.compute(ByteBuffer, int, int)]
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:991)
        at com.oracle.svm.hosted.code.CompileQueue.doCompile(CompileQueue.java:922)
        at com.oracle.svm.hosted.code.CompileQueue$CompileTask.run(CompileQueue.java:259)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.NullPointerException
        at com.oracle.svm.hosted.code.CompileQueue.defaultCompileFunction(CompileQueue.java:937)
        ... 9 more
Error: Image build request failed with exit status 1
```

This works if it is packaged with JDK-8 (maven:3.6.3-jdk-8) and compiled with the JDK-8 version of graalvm oracle/graalvm-ce:19.3.1-java8.

I understand micronaut-kafka is advertised as supporting graalvm, but this is currently broken with JDK-11.

You get this error with an empty project which only has simple consumer.

**Comment by graemerocher** [comment]
@mhaddon could you report the issue to https://github.com/oracle/graal/issues and reference back this issue. This looks like a GraalVM compiler bug that I am not sure we have much ability to fix on our end.
